name: Grant S3 Access

on:
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'The name of the S3 bucket'
        required: true
        type: string
      username:
        description: 'name of the user to grant access'
        required: true
        type: string

jobs:
  grant-access:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #      aws-region: 'us-east-2'
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: .


      - name: Terraform Apply
        run: terraform apply -var bucket_name=${{ github.event.inputs.bucketName }} -var user_name=${{ github.event.inputs.username }} -auto-approve
        working-directory: .

