name: Grant S3 Access

on:
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'The name of the S3 bucket'
        required: true
        type: string
      userEmail:
        description: 'Email of the user to grant access'
        required: true
        type: string

jobs:
  grant-access:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2 # Update to your region

      - name: Notify User
        run: |
          echo "User ${{ inputs.userEmail }} has been granted access to S3 bucket ${{ inputs.bucketName }}."
